import { PrismaClient } from "@prisma/client";

declare global {
  var prisma: PrismaClient | undefined;
}

export const db =
  globalThis.prisma ||
  new PrismaClient({
    // Log the underlying SQL commands that are generated by Prisma.
    log: ["query"],
  });

if (process.env.NODE_ENV !== "production") globalThis.prisma = db;
